version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            npm install

      - run:
          name: Update Browserslist
          command: |
            npx browserslist@latest --update-db

      - run:
          name: Build Project
          command: |
            CI=false npm run build
      - run:
          name: check
          command: |
            echo "$circleci_docker_password"

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: |
            docker build -t shadabmaliks/circleci_react:latest .

      - run:
          name: Log in to Docker Hub
          command: echo "$circleci_docker_password" | docker login -u "$circelci_docker_username" --password-stdin

      - run:
          name: Push Docker Image
          command: |
            docker push shadabmaliks/circleci_react:latest
             # Save the Docker image as a .tar file
      - run:
          name: Save Docker Image as TAR
          command: |
            docker save -o shadabmaliks_circleci_react.tar shadabmaliks/circleci_react:latest

      # Store the .tar file as an artifact
      - store_artifacts:
          path: shadabmaliks_circleci_react.tar
          destination: docker-image

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context:
            - my_context
 
