version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
          
            npm install

      - run:
          name: Build Project
          command: |
            
            npm run build

      - setup_remote_docker:
          # version: 20.10.12  # Updated to a more stable version
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: |
            
            docker build -t shadabmaliks/circleci_react:latest .

      - run:
          name: Log in to Docker Hub
          command: echo "${CIRCLECI_DOCKER_PASSWORD}" | docker login -u "${CIRCLECI_DOCKER_USERNAME}" --password-stdin

      - run:
          name: Push Docker Image
          command: |
            docker push shadabmaliks/circleci_react:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
