name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Create service account key file
      run: |
        # Write the JSON secret to the service account key file
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/gcloud-service-key.json
        # Optionally, verify the contents of the file (debugging)
        cat $HOME/gcloud-service-key.json

    - name: Authenticate with Google Cloud
      run: |
        # Authenticate using the service account key file
        gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json
        # Set the project
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Kubectl
      run: |
        # Set up kubectl using GKE credentials
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }}

    - name: Deploy to GKE
      run: |
        # Apply the Kubernetes deployment YAML
        kubectl apply -f k8s/react-deployment.yaml
