name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Create service account key file
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/gcloud-service-key.json
        cat $HOME/gcloud-service-key.json  # Verify the file content (for debugging)

    - name: Authenticate with Google Cloud
      run: |
        gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/react-deployment.yaml  # Ensure your manifest is located in the 'k8s' folder
